Andrew King
turingschool/mod-0-project-be pull request #21
Opened 2022-02-13 00:57 UTC by devAndrewK

2022-02-15 15:02 UTC, philmccarthy requested changes
Hi @devAndrewK,

There are a couple things missing that needs to be addressed before your project is complete:

## To do

- [ ] final_prep refactoring exercise (first section)
- [ ] `section2/ exercises` from https://github.com/turingschool/mod-0-project-be/tree/main/section2#if-statement-and-conditional-lessons are missing. Please confirm you went through these exercises. It's ok if you don't have the files to add.

Submit updates by EOD tomorrow (Wed 2/16).

## Feedback

Other than those 2 things, your project work looks really good. You clearly have a solid technical foundation and I'm confident you'll be ready to tackle Mod 1. I left a few comments throughout, so take a look and feel free to ask any questions in replies.

I would've liked to see you update the READMEs throughout the project, checking off items in the markdown as you went. _Not_ doing that might have contributed to you accidentally skipping a couple sections?

2022-02-16 10:01 UTC, devAndrewK commented
As far as I could tell, I didn't see anything that could be factored further in section 1.

2022-02-16 10:02 UTC, devAndrewK commented on section3/exercises/hashes.rb
> +{
So the main problem was the inconsistent indentation of the key-value pairs?

2022-02-16 10:03 UTC, devAndrewK commented on section3/exercises/hashes.rb
> +{
Good to know, I know other languages do it that way, so I probably got the idea from somewhere else.

2022-02-16 10:09 UTC, devAndrewK commented on section3/exercises/arrays.rb
> +def add_broccoli (array)
I could use a gets.chomp to get input and .push that into the array, instead of the hard coded string.

2022-02-16 10:14 UTC, devAndrewK commented
Also I honestly didn't make the connection between the README file being what is read from the browser. I thought the README was just a copy. I had tried doing the checkmarks but they weren't saving however I was doing it.

2022-02-16 15:40 UTC, philmccarthy commented on section3/exercises/hashes.rb
> +{
And the opening curly bracket should also be indented

2022-02-16 15:45 UTC, philmccarthy commented
Hey @devAndrewK, the section about refactoring relates to making _any_ changes to section 1-3 exercises. Your commit history shows you haven't made any changes to those files since you completed them originally.

You can't think of any updates to make in all of those exercises now that you've learned more about Ruby, different methods, style conventions? It doesn't need to be much, but this is a required exercise.

2022-02-16 21:34 UTC, devAndrewK commented
I actually did misinterpret what you meant by section 1; please let me know if my additional changes were sufficient.

2022-02-17 00:52 UTC, philmccarthy commented
Thanks Andrew. Good to go.

Other than the sections you skipped, your project looked solid. I appreciated your reflections throughout Mod 0. And I wish you all the best moving forward! Good luck in Mod 1 🙂

2022-02-17 00:52 UTC, closed without merging